# Site settings
title: GitHub Pages / React / Single-Page App Demo
description: Demonstrating React in Tucson
email: ghpages-react-spa@xkq.io

baseurl: ''
url: http://grs.xkq.io
twitter_username: dmsnell23
github_username:  dmsnell

# Build settings
markdown: kramdown
production: true
